name: Deploy to AWS Amplify
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Amplify
        uses: aws-actions/aws-amplify-github-action@v0.5.0
        with:
          app_id: ${{ secrets.AMPLIFY_APP_ID }}
          branch_name: production
          commit_id: ${{ github.sha }}